name: npm-publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  npm-publish:
    name: npm-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: package
      run: |
        npm install
        npm run package
    - name: publish
      working-directory: ./app
      run: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}